# Generated by Django 3.1.8 on 2021-04-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='id',
        ),
        migrations.AlterField(
            model_name='auth',
            name='userDescription',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auth',
            name='userName',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
