templateLogin = 'login/login.html'
templateSignUp = 'signUp/signUp.html'
templateHolder = 'holder/index.html'
templateDetail = 'contestDetail/index.html'
templateCreate = 'createContest/index.html'
templateStatus = 'contestStatus/index.html'
templateParticipant = 'ContestParticipant/index.html'
