# Generated by Django 3.1.8 on 2021-04-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.TextField()),
                ('userDescription', models.TextField()),
                ('userAge', models.TextField(default='25 noi banh chung')),
            ],
        ),
    ]
